version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 15432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
    image: anemperfeina:1.0
    user: root
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/anem-per-feina/
    entrypoint:
      - invoke
      - wait-for
      - db:5432
      - migrate
      - runserver
      - --debug

  frontoffice:
    build: ./frontoffice/
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./frontoffice/:/frontoffice/
      - /frontoffice/node_modules

volumes:
  postgres_data:
